# ./well-architected-iac-analyzer/finch-compose.yaml
version: '3.8'

services:
  frontend:
    build:
      context: ./ecs_fargate_app/frontend
      dockerfile: ../finch/frontend.Dockerfile
    ports:
      - "8080:8080"
    environment:
      - VITE_API_URL=http://backend:3000
    depends_on:
      - backend

  backend:
    build:
      context: ./ecs_fargate_app/backend
      dockerfile: ../finch/backend.Dockerfile
    ports:
      - "3000:3000"
    environment:
      - WA_DOCS_S3_BUCKET=\${WA_DOCS_S3_BUCKET}
      - KNOWLEDGE_BASE_ID=\${KNOWLEDGE_BASE_ID}
      - MODEL_ID=\${MODEL_ID}
      - AWS_REGION=\${AWS_REGION}
      - FRONTEND_URL=http://localhost:8080

volumes:
  npm-cache:
    external: true